# Q1.what is the total revenue generated by male vs female customer?

select gender, sum(purchase_amount) as total_revenue_generated
from customers
group by gender;

# Q2. which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customers
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customers);

# Q3. which are the top 5 products with the highest average review ratings?

select item_purchased, round(avg(review_rating), 2) as avg_rating
from customers 
group by item_purchased
order by avg_rating desc
limit 5;

# Q4. Compare the average purchase amount between standard and express shipping.

select round(avg(purchase_amount), 2) as avg_purchase_amount, shipping_type
from customers
where shipping_type in ('Express', 'Standard')
group by shipping_type;

# Q5. Do subscribed customers spend more? compare the average spend and total revenue between subscribers and non-subscribers.

select subscription_status as subscribed, count(customer_id) as total_customers, avg(purchase_amount) as avg_spending, sum(purchase_amount) as total_revenue
from customers
group by subscription_status
order by avg_spending, total_revenue desc;

# Q6. which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased, round(sum(case when discount_applied = 'Yes' then 1 else 0 end) / count(*) * 100, 2) as perc_purchase
from customers
group by item_purchased
order by perc_purchase desc
limit 5;

# Q7. segment customers into New, Recurring, and loyal based on their total number of previous purchases and show the count of each segment 

with customer_type as (
select customer_id, previous_purchases,
case 
	when previous_purchases = 1 then 'New'
	when previous_purchases  between 2 and 10 then 'Returning'
	else 'loyal' 
    end as customer_segment
from customers 
)

select customer_segment, count(*) as 'Number of Customer'
from customer_type
group by customer_segment;


# Q8. what are the top 3 most purchased products within each category?

with item_counts as (
select category, 
item_purchased, 
count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc) as item_rank
from customers
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

# Q9. are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from customers
where previous_purchases > 5
group by subscription_status;

# Q10. what is the revenue contribution of each age group

select age_group,
sum(purchase_amount) as total_revenue
from customers
group by age_group
order by total_revenue desc;


